# Generated by Django 4.1.4 on 2022-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url_Image', models.CharField(max_length=200)),
                ('Nom', models.TextField()),
                ('stock', models.IntegerField()),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
